# get access token 
POST https://globalapi.solarmanpv.com/account/v1.0/token?appId={{solarManAppId}}
Content-Type: application/json

{ 
   "appSecret": "{{appSecret}}", 
   "email": "{{solarManAppEmail}}", 
   "password": "{{solarManAppPassword}}" 
}

> {% client.global.set("auth_token", response.body.access_token) %}


### Get Station

POST https://globalapi.solarmanpv.com/station/v1.0/list?language=en
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{ 

}

> {% client.global.set("stationId", response.body.stationList[0].id) %}



### Get Realtime Info 

POST https://globalapi.solarmanpv.com/station/v1.0/realTime?language=en&1721367391216
Authorization: Bearer {{auth_token}} 
Content-Type: application/json

{
  "stationId": {{stationId}}
}

